In [3]:
import numpy as np
import matplotlib.pyplot as plt
from numpy.linalg import solve
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets


In [4]:
X = [0,1]
Y = [0,2]

A = np.array([[1,X[0],X[0]**2,X[0]**3],
               [1,X[1],X[1]**2,X[1]**3],
               [0,1,2*X[0],3*X[0]**2],
               [0,1,2*X[1],3*X[1]**2]])

Vx = np.linspace(X[0], X[1], 100)

@interact(alpha0=(-20,20,1),alpha1=(-20,20,1),y0=(-5,5,0.5))
def g(alpha0,alpha1,y0):
    b=np.array([y0,Y[1],alpha0,alpha1])
    Sol = solve(A, b)
    plt.plot(X,[y0,Y[1]],marker='*',markersize=20.)
    def P(x): return Sol[0] + Sol[1]*x + Sol[2]*x**2 + Sol[3]*x**3
    plt.plot(Vx,P(Vx), "-r",linewidth=4.5)
    plt.axis('equal')

interactive(children=(IntSlider(value=0, description='alpha0', max=20, min=-20), IntSlider(value=0, descriptio…

In [7]:
Mat0 = np.zeros((8,8))
Mat0[0,2:4] = [1,2]
print(Mat0)

[[0. 0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
