In [1]:
import numpy as np
import math as ma
import matplotlib.pyplot as plt
from numpy.linalg import solve # pour travailler des matrix

In [ ]:
X = [2,10,2,10]
Y=[10,10,11,11]

A = np.array([[X[0],1,0,0,0,0,0,0],
             [X[1],1,0,0,0,0,0,0],
             [0,0,X[0],1,0,0,0,0],
             [0,0,X[1],1,0,0,0,0],
             [0,0,0,0,X[0],1,0,0],
             [0,0,0,0,X[1],1,0,0],
             [0,0,0,0,0,0,X[0],1],
             [0,0,0,0,0,0,X[1],1]])

b = np.array([Y[0],Y[1],Y[2],Y[3],Y[0],Y[3],Y[1],Y[2]])

S = solve(A, b)

def A(x): return S[0]*x+S[1]
def B(x): return S[2]*x+S[3]
def C(x): return S[4]*x+S[5]
def D(x): return S[6]*x+S[7]

Va = np.linspace(X[0], X[1], 100)
Vb = np.linspace(X[1], X[2], 100)
Vc = np.linspace(X[2], X[3], 100)
Vd = np.linspace(X[3], X[0], 100)
plt.plot(X, Y, "+r")
plt.plot(Va, A(Va), "-b")
plt.plot(Vb, B(Vb), "-y")
plt.plot(Vc, C(Vc), "-g")
plt.plot(Vd, D(Vd), "-p")

print(S)

In [2]:
X = [1,1,3]
Y = [3,1,2]

pointEye = [(1,3),(1,1),(3,2)]
def drawEye(points):
    if len(points) <= 3:
        x0 = points[0][0]
        y0 = points[0][1]
        x1 = points[1][0]
        y1 = points[1][1]
        x2 = points[2][0]
        y2 = points[2][1]
        A = np.array([[x0,1,0,0],[x2,1,0,0],[0,0,x1,1],[x2,1,-x2,-1]])
        b = np.array([y0,y2,y1,0])
        S = solve(A, b)
        Va = np.linspace(x0, x2, 100)
        Vb = np.linspace(x1, x2, 100)
        def A(x): return S[0]*x+S[1]
        def B(x): return S[2]*x+S[3]
        plt.plot(X, Y, "+r")
        plt.plot(Va, A(Va), "-b")
        plt.plot(Vb, B(Vb), "-g")
        plt.axis('equal')

drawEye(pointEye)

In [28]:
pointBordCup = [(1,3),(3,3),(4,2),(3,1)]
def drawBordCup(points):
    if len(points) <= 4:
        x0 = points[0][0]
        y0 = points[0][1]
        x1 = points[1][0]
        y1 = points[1][1]
        x2 = points[2][0]
        y2 = points[2][1]
        x3 = points[3][0]
        y3 = points[3][1]
        alpha1 = 2
        A = np.array([[1,x0,0,0,0],
                      [1,x1,0,0,0],
                      [0,x1,0,-x1,-2*x1],
                      [0,0,1,x2,x2**2],
                      [0,0,0,1,2*x2]])
        b = np.array([y0,y1,alpha1,y2,y3])
        S = solve(A, b)
        print(S)
        Va = np.linspace(x0, x1, 10)
        Vb = np.linspace(x1, x3, 10)
        def A(x): return S[0]+S[1]*x
        def B(x): return S[2]+S[3]*x+S[4]*x**2
        #plt.plot(X, Y, "+r")
        plt.plot(Va, A(Va), "*b")
        plt.plot(Vb, B(Vb), "*g")
        plt.axis('equal')

drawBordCup(pointBordCup)

[ 3.00000000e+00  1.48029737e-16  2.44444444e+00 -1.22222222e+00
  2.77777778e-01]


In [14]:
A = np.array(np.zeros((10,10)))
print(A)
mat0[0,2:8] = [1,2]

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


ValueError: could not broadcast input array from shape (2,) into shape (6,)